site_name: Michael Colletti 
site_author: Michael Colletti 
copyright: Creative Possibilities Inc. 2024
remote_name: 
site_description: For Creating Documentation using Github
repo_url: https://github.com/michaelcolletti/modes-in-genres
repo_name: modes-in-genres
edit_uri: '?query=/docs'

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - json
        - python
    locale: en
#    custom_dir: custom
    nav_style: dark
#    color_scheme: 
#    static_templates:
#        - sitemap.html
    include_sidebar: true
nav:
  - Home: README.md
  - Docs: docs.md
  - Project: project.md
